spring.application.name=app
#elige un puerto libre
server.port=8090
#8082,8090,8181,8888,9090

# Bse de datos
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=system
spring.datasource.password=system
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver